name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installation des dépendances
        run: npm ci

      - name: Linter ESLint
        run: npm run lint

      - name: Installer Playwright avec dépendances
        run: npx playwright install --with-deps

      - name: Tests end-to-end Playwright
        run: npm run dev-test
      
      - name: Générer la couverture Jest
        run: npm run coverage

  sonarcloud:
    name: Analyse SonarCloud
    runs-on: ubuntu-latest
    needs: lint-and-test

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installer les dépendances
        run: npm ci

      - name: Lancer l’analyse SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 

      - name: SonarCloud Quality Gate Check
        uses: SonarSource/sonarcloud-quality-gate-action@v1.1.1
        with:
          scanMetadataReportFile: .scannerwork/report-task.txt
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}